# Generated by Django 2.2.8 on 2020-02-26 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Add Class Title', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentsInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(default=None, help_text='Select Student', on_delete=django.db.models.deletion.CASCADE, related_name='studentsinclass_student', to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(default=None, help_text='Select Class', on_delete=django.db.models.deletion.CASCADE, related_name='studentsinclass_class', to='students.StudentClass')),
            ],
            options={
                'verbose_name': 'Stundents in Class',
                'verbose_name_plural': 'Stundents in Class',
            },
        ),
    ]
